backend:
  name: github
  repo: dileepkr1996c-arch/blog.yougrowonline
  branch: main
  site_domain: blog.yougrowonline.in

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: .md
    format: frontmatter
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image URL", name: "image", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Category"
        name: "categories"
        widget: "select"
        options: ["web-development", "ecommerce", "marketing", "seo", "ai", "design"]
        required: false
